"""empty message

Revision ID: 723427db1293
Revises: 3bcef9884f11
Create Date: 2019-09-09 14:24:53.080821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723427db1293'
down_revision = '3bcef9884f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_doctor_time', 'reception', ['day', 'time', 'doctor_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_doctor_time', 'reception', type_='unique')
    # ### end Alembic commands ###
